### ISSUE TITLE
/lib64/libm.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by ydy1127** [RitchieLabIGH/IRFinder#38]
Dear IRFinder's team,

Hi, When I run the following the command `IRFinder BAM -r /data1/yuandy/biosoft/IRFinder-2.0.1/REF/tair10 -d test Unsorted.bam,` I encounter an error message.

```
/lib64/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/_MEISMsNS9/tflite_runtime/_pywrap_tensorflow_interpreter_wrapper.cpython-36m-x86_64-linux-gnu.so)
Traceback (most recent call last):
  File "irfinder_cnn.py", line 92, in <module>
  File "irfinder_cnn.py", line 85, in main
  File "irfinder_cnn.py", line 77, in main
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "actions/models.py", line 4, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "tflite_runtime/interpreter.py", line 36, in <module>
ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/_MEISMsNS9/tflite_runtime/_pywrap_tensorflow_interpreter_wrapper.cpython-36m-x86_64-linux-gnu.so)
[48258] Failed to execute script irfinder_cnn
```

It would be great if you could let me know.

Best,
Danyang Yuan

**Comment by CloXD** [comment]
Hello, 
how are you running the software? Docker, Singularity or with a local installation? If the latest, you might have missed some dependencies, listed in the Dockerfile.
Cheers
Claudio

**Comment by ydy1127** [comment]
Hi Claudio,

Thank you for the update.
Because I don't have root account, I can't deploy and use Docker and Singularity. I use the IRFinder-2.0.1 with a local installation.

The command `IRFinder BuildRefProcess` can be executed successfully. When I run the following the command` IRFinder BAM -r /data1/yuandy/biosoft/IRFinder-2.0.1/REF/tair10 -d test Unsorted.bam`, I encounter an error message as shown above.

According to the log message in irfinder.stdout, the software seems to stop at building the CNN model.

```
[  Mon Jan 8 08:35:10 UTC 2024  ] IRFinder BAM analysis completed
---
---                                                                                                                                   
[  Mon Jan 8 08:35:10 UTC 2024  ] Running CNN validator
```
Although the program stopped running, I also got a few output files. 
```
IRFinder-ChrCoverage.txt
IRFinder-IR-nondir.txt
IRFinder-JuncCount.txt
IRFinder-ROI.txt
IRFinder-SpansPoint.txt
```
In addition, I have a problem, I used the RNAseq data from paired-end sequencing, but only output *nondir.txt file.

It would be great if you could let me know.

Best,
Danyang Yuan

**Comment by CloXD** [comment]
Hi  Danyang Yuan,
actually, you don't need admin privileges to execute singularity images. 
For what concerns the presence of only the *nondir.txt, it's probably because your reads are not directional or the software doesn't consider them as directional ( the information about the directionality is included in the standard output ). 
Cheers,
Claudio

**Comment by ydy1127** [comment]
Hi Claudio,

Thank you for the reply. I successfully deployed Docker on the server and had IRFinder running smoothly. I still have two questions for you to explain about the result file

(1) How to determine whether a set of RNAseq data is directional reads? 
(2) ” In case there is an overlapping feature on the opposite strand, it's marked as anti-near or anti-over ( depending on if is overlapping or is just in the neighbours ).“ I am confused about this definition. For example, the intron of Arabidopsis AT1G01010 gene does not overlap with any region, but is defined as anti-near.

It would be great if you could let me know.

Best,
Danyang Yuan
